"""Add players, inventory, clans and devices models

Revision ID: 141f59cb6c53
Revises:
Create Date: 2025-07-13 00:30:16.374345

"""
import sqlalchemy as sa
from alembic import op
from collections.abc import Sequence
from sqlalchemy.dialects import postgresql
from typing import Union


# revision identifiers, used by Alembic.
revision: str = "141f59cb6c53"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clans",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_clan_name", "clans", ["name"], unique=False)
    op.create_table(
        "players",
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("credential", sa.String(), nullable=False),
        sa.Column("last_session", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_purchase", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_spent", sa.Float(), nullable=True),
        sa.Column("total_refund", sa.Float(), nullable=True),
        sa.Column("total_transactions", sa.Integer(), nullable=True),
        sa.Column("total_playtime", sa.Float(), nullable=True),
        sa.Column("level", sa.Integer(), nullable=True),
        sa.Column("xp", sa.Float(), nullable=True),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("gender", sa.String(), nullable=False),
        sa.Column("birthdate", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "active_campaigns",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("clan_id", sa.String(), nullable=True),
        sa.Column("created", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["clan_id"], ["clans.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("player_id"),
    )
    op.create_index(
        "idx_players_active_campaigns_gin",
        "players",
        ["active_campaigns"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "idx_players_clan_id", "players", ["clan_id"], unique=False
    )
    op.create_index(
        "idx_players_country", "players", ["country"], unique=False
    )
    op.create_index("idx_players_level", "players", ["level"], unique=False)
    op.create_index(
        op.f("ix_players_player_id"), "players", ["player_id"], unique=False
    )
    op.create_table(
        "devices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=True),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("carrier", sa.String(), nullable=True),
        sa.Column("firmware", sa.String(), nullable=True),
        sa.Column("created", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.player_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_device_player", "devices", ["player_id"], unique=False
    )
    op.create_index(
        op.f("ix_devices_player_id"), "devices", ["player_id"], unique=False
    )
    op.create_table(
        "inventory",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=True),
        sa.Column("item_key", sa.String(), nullable=False),
        sa.Column("item_count", sa.Integer(), nullable=True),
        sa.Column("created", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.player_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_inventory_player_item",
        "inventory",
        ["player_id", "item_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_item_key"), "inventory", ["item_key"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_player_id"),
        "inventory",
        ["player_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inventory_player_id"), table_name="inventory")
    op.drop_index(op.f("ix_inventory_item_key"), table_name="inventory")
    op.drop_index("idx_inventory_player_item", table_name="inventory")
    op.drop_table("inventory")
    op.drop_index(op.f("ix_devices_player_id"), table_name="devices")
    op.drop_index("idx_device_player", table_name="devices")
    op.drop_table("devices")
    op.drop_index(op.f("ix_players_player_id"), table_name="players")
    op.drop_index("idx_players_level", table_name="players")
    op.drop_index("idx_players_country", table_name="players")
    op.drop_index("idx_players_clan_id", table_name="players")
    op.drop_index(
        "idx_players_active_campaigns_gin",
        table_name="players",
        postgresql_using="gin",
    )
    op.drop_table("players")
    op.drop_index("idx_clan_name", table_name="clans")
    op.drop_table("clans")
    # ### end Alembic commands ###
